apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocp4-kt-anyuid
  namespace: ocp4-kt
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
